seed: 9419
save_model: true
use_wandb: false
local_rank: 0
enable_cuda_optimizations: true
mixed_precision: bf16

dataset:
  input_dataset: "conjuring92/dpc-mix-pretrain-a05"

model:
  backbone_path: google/byt5-large
  max_length: 1024
  use_gradient_checkpointing: true
  compile_model: false
      
train_params:
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  num_train_epochs: 3
  gradient_accumulation_steps: 1

  warmup_pct: 0.2
  lr_decay_target: 1.0 # Constant LR
  eval_frequency: 2000
  use_ema: false
  ema_decay: 0.999
  label_smoothing: 0.0

  use_awp: true # true
  awp_adv_lr: 1.0
  awp_adv_eps: 0.001
  awp_trigger_epoch: 0

augmentation:
  name_swap_prob: 0.0  # set to 0.0 to disable
  lower_case_prob: 0.0   # set to 0.0 to disable

optimizer:
  name: AdamW

  lr: 6e-5
  lr_encoder: 6e-5
  lr_decoder: 6e-5

  weight_decay: 1e-2
  max_grad_norm: 0.3 # 1000 # 0.3

  adam_beta_1: 0.9
  adam_beta_2: 0.98
  adam_epsilon: 1e-8

generation:
  max_new_tokens: 384 # 512
  do_sample: true
  top_k: 50
  top_p: 1.0
  temperature: 0.1

outputs:
  model_dir: /workspace/models/large_cpt_mix_a04_good

wandb:
  project: dpc-dev-a1
  run_name: dpc-pretrain-xl-mix-a05