seed: 9610
save_model: true
use_wandb: false
local_rank: 0
enable_cuda_optimizations: true
mixed_precision: bf16

onomasticon_dataset: conjuring92/dpc-onomasticon-polysemy
onomasticon_file: onomasticon.parquet
polysemic_file: polysemy.parquet
single_variant_file: onomasticon_single_variant.parquet

dataset:
  input_dataset: "conjuring92/dpc-mix-gold-m2"

model:
  backbone_path: /workspace/models/a05_cpt_xl_final/checkpoints/step_8000
  max_length: 1024
  use_gradient_checkpointing: true
  compile_model: false
      
train_params:
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  num_train_epochs: 3
  gradient_accumulation_steps: 16

  warmup_pct: 0.1
  lr_decay_target: 0.1
  eval_frequency: 900
  use_ema: true
  ema_decay: 0.9995
  label_smoothing: 0.01

  use_awp: false # true
  awp_adv_lr: 1.0
  awp_adv_eps: 0.001
  awp_trigger_epoch: 0

augmentation:
  name_swap_prob: 0.3 # set to 0.0 to disable

optimizer:
  name: AdamW8bit

  lr: 4e-5
  lr_encoder: 4e-5
  lr_decoder: 4e-5

  weight_decay: 1e-2
  max_grad_norm: 0.3

  adam_beta_1: 0.9
  adam_beta_2: 0.98
  adam_epsilon: 1e-8

generation:
  max_new_tokens: 384 # 512
  do_sample: true
  top_k: 50
  top_p: 1.0
  temperature: 0.1

outputs:
  model_dir: /workspace/models/a05_cpt_xl_m2_ff
wandb:
  project: dpc-dev-a1
  run_name: dpc-continue-xl-m2-ff